name: Deploy GCP

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: server-update
    steps:
      - name: Execute Deployment Script via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: 22
          script: |
            cd /var/www/Nime-nime
            git pull origin main
            npm ci
            npx prisma migrate deploy
            npm run build
            pm2 restart nime-nime --update-env
            pm2 restart nimenime-bot --update-env